# Copyright © 2025 Dev & Software. All rights reserved.

# THIS SOFTWARE IS PROPRIETARY AND CONFIDENTIAL. UNAUTHORIZED COPYING, DISTRIBUTION, MODIFICATION,
# REVERSE ENGINEERING, OR DISCLOSURE IS STRICTLY PROHIBITED.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
# LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR ITS USE.

# frozen_string_literal: true

ASSETS_PATH = Rails.public_path.join('assets').freeze
DIRECTORIES_PATH = ASSETS_PATH.join('**/').freeze
CONTROLLERS_PATH = ASSETS_PATH.join('controllers', '**', '*.js').freeze
APPLICATION_JS_PATH = ASSETS_PATH.join('application-*.js').freeze

Rake::Task['assets:precompile'].enhance do
  FileUtils.rm_rf Dir.glob(DIRECTORIES_PATH.join('*.{rb,yml,ts,json,md}'))
  Dir[DIRECTORIES_PATH].reverse_each { Dir.rmdir(_1) if Dir.empty?(_1) }
  Dir.glob([CONTROLLERS_PATH, APPLICATION_JS_PATH]).each do |path|
    File.write(path, Terser.compile(File.read(path)))
  end
end
