detectors:
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    max_params: 5
  TooManyStatements:
    max_statements: 15
    exclude:
      - inherited
  TooManyInstanceVariables:
    max_instance_variables: 9
  DuplicateMethodCall:
    max_calls: 9
  RepeatedConditional:
    max_ifs: 15
  TooManyMethods:
    max_methods: 30
  NestedIterators:
    max_allowed_nesting: 3
  BooleanParameter:
    exclude:
      - Component
  Attribute:
    exclude:
      - prefixed
      - inverse_entity
  ControlParameter:
    exclude:
      - initialize
      - build
  UtilityFunction:
    enabled: false # TODO: fix this smell
  FeatureEnvy:
    enabled: false # TODO: fix this smell
  InstanceVariableAssumption:
    exclude:
      - Specs::Dummy
      - Tokens::Variable
directories:
  app:
    InstanceVariableAssumption:
      enabled: false
exclude_paths:
  - db/migrate
  - spec/dummy
