require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
Style/Documentation:
  Enabled: false
Style/ReturnNil:
  Enabled: true
Style/HashEachMethods:
  AllowedReceivers:
    - enum
    - attribute
Layout/LineLength:
  Max: 100
RSpec/ExampleLength:
  Max: 15
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - resource
    - after_bundle
    - setup
    - after_initialize
    - put
    - post
    - get
    - context
    - namespace
    - class_eval
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 300
RSpec/MultipleExpectations:
  Max: 2
Metrics/AbcSize:
  Max: 60
Metrics/ParameterLists:
  Max: 8
Performance/MethodObjectAsBlock:
  Enabled: false
AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*
