require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
Style/Documentation:
  Enabled: false
Style/ReturnNil:
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Layout/LineLength:
  Max: 100
RSpec/ExampleLength:
  Max: 15
Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - resource
    - after_bundle
    - setup
    - after_initialize
    - put
    - post
    - get
    - context
    - namespace
    - class_eval
Metrics/MethodLength:
  Max: 50
Metrics/ClassLength:
  Max: 270
RSpec/MultipleExpectations:
  Max: 2
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/AbcSize:
  Max: 76
Metrics/ParameterLists:
  Max: 7
Performance/MethodObjectAsBlock:
  Enabled: false
AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Exclude:
    - spec/dummy/**/*
    - vendor/**/*
