image: ruby:3.0

pipelines:
  default:
    - parallel:
      - step:
          name: Lint code
          caches:
            - bundler
          script:
            - bundle install --path .bundle
            - bundle exec rubocop
      - step:
          name: Code smells
          caches:
            - bundler
          script:
            - bundle install --path .bundle
            - bundle exec reek
      - step:
          name: Test
          caches:
            - bundler
          script:
            - bundle install --path .bundle
            - bundle exec rspec
definitions:
  caches:
    bundler: .bundle
