services:
  web:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - storage-data:/back-office/storage
      - clamav-data:/var/lib/clamav
volumes:
  clamav-data:
  storage-data:
