# frozen_string_literal: true

$LOAD_PATH.push File.expand_path('lib', __dir__)

require 'schematics/version'

Gem::Specification.new do |spec|
  spec.name = 'schematics'
  spec.version = Schematics::VERSION
  spec.authors = ['maxence.derous']
  spec.email = ['maxence.derous@gmail.com']
  spec.homepage = 'http://mygemserver.com'
  spec.summary = 'Summary of Schematics.'
  spec.description = 'Description of Schematics.'
  spec.license = 'Private'
  spec.required_ruby_version = '>= 3.1.1'
  spec.metadata['allowed_push_host'] = 'http://mygemserver.com'
  spec.metadata['rubygems_mfa_required'] = 'true'
  spec.files = Dir['{app,config,db,lib}/**/*', 'README.md']
  spec.add_development_dependency 'bootsnap', '~> 1.11.1'
  spec.add_development_dependency 'capybara', '~> 3.36.0'
  spec.add_development_dependency 'i18n-tasks', '~> 1.0.9'
  spec.add_development_dependency 'pg', '~> 1.3.5'
  spec.add_development_dependency 'reek', '~> 6.1.0'
  spec.add_development_dependency 'rspec-its', '~> 1.3.0'
  spec.add_development_dependency 'rubocop', '~> 1.27.0'
  spec.add_development_dependency 'rubocop-performance', '~> 1.13.3'
  spec.add_development_dependency 'rubocop-rails', '~> 2.14.2'
  spec.add_development_dependency 'rubocop-rake', '~> 0.6.0'
  spec.add_development_dependency 'rubocop-rspec', '~> 2.9.0'
  spec.add_development_dependency 'rubocop-thread_safety', '~> 0.4.4'
  spec.add_development_dependency 'scss_lint', '~> 0.59.0'
  spec.add_development_dependency 'simplecov', '~> 0.21.2'
  spec.add_development_dependency 'slim_lint', '~> 0.22.1'
  spec.add_development_dependency 'webpacker', '~> 5.4.3'
  spec.add_development_dependency 'zeitwerk', '~> 2.5.3'
  spec.add_dependency 'aasm', '~> 5.2.0'
  spec.add_dependency 'active_link_to', '~> 1.0.5'
  spec.add_dependency 'active_model_serializers', '~> 0.10.13'
  spec.add_dependency 'active_record_doctor', '~> 1.9.0'
  spec.add_dependency 'active_storage_base64', '~> 1.2.0'
  spec.add_dependency 'active_storage_validations', '~> 0.9.7'
  spec.add_dependency 'annotate', '~> 3.2.0'
  spec.add_dependency 'bcrypt', '~> 3.1.16'
  spec.add_dependency 'better_errors', '~> 2.10.0beta2'
  spec.add_dependency 'binding_of_caller', '~> 1.0.0'
  spec.add_dependency 'bootstrap-email', '~> 1.1.2'
  spec.add_dependency 'brakeman', '~> 5.2.2'
  spec.add_dependency 'cancancan', '~> 3.3.0'
  spec.add_dependency 'chartkick', '~> 4.1.3'
  spec.add_dependency 'chroma', '~> 0.2.0'
  spec.add_dependency 'client_side_validations', '~> 20.0.2'
  spec.add_dependency 'client_side_validations-simple_form', '~> 14.1.0'
  spec.add_dependency 'country_select', '~> 7.0.0'
  spec.add_dependency 'database_consistency', '~> 1.1.12'
  spec.add_dependency 'date_validator', '~> 0.12.0'
  spec.add_dependency 'easy_translate', '~> 0.5.1'
  spec.add_dependency 'elasticsearch', '~> 7.17.0'
  spec.add_dependency 'friendly_id', '~> 5.4.2'
  spec.add_dependency 'groupdate', '~> 6.1.0'
  spec.add_dependency 'grover', '~> 1.1.1'
  spec.add_dependency 'hiredis', '~> 0.6.3'
  spec.add_dependency 'humanize', '~> 2.5.1'
  spec.add_dependency 'i18n-beginning_of_week', '~> 0.1.0'
  spec.add_dependency 'i18n-inflector', '~> 2.6.7'
  spec.add_dependency 'image_processing', '~> 1.12.2'
  spec.add_dependency 'interactor', '~> 3.1.2'
  spec.add_dependency 'json-schema', '~> 2.8.1'
  spec.add_dependency 'js-routes', '~> 2.2.3'
  spec.add_dependency 'jwt', '~> 2.3.0'
  spec.add_dependency 'loaf', '~> 0.10.0'
  spec.add_dependency 'mini_magick', '>= 4.11.0'
  # TODO: remove net-* gems when https://github.com/mikel/mail/pull/1439 is merged
  spec.add_dependency 'net-imap', '~> 0.2.3'
  spec.add_dependency 'net-pop', '~> 0.1.1'
  spec.add_dependency 'net-smtp', '~> 0.3.0'
  spec.add_dependency 'oj', '~> 3.13.11'
  spec.add_dependency 'pagy', '~> 5.10.1'
  spec.add_dependency 'paper_trail', '~> 12.3.0'
  spec.add_dependency 'paranoia', '~> 2.6.0'
  spec.add_dependency 'phonelib', '~> 0.6.58'
  spec.add_dependency 'rack-attack', '~> 6.6.1'
  spec.add_dependency 'rack-cors', '~> 1.1.1'
  spec.add_dependency 'rack-mini-profiler', '~> 2.3.4'
  spec.add_dependency 'rails', '~> 6.1.5'
  spec.add_dependency 'rails-erd', '~> 1.6.1'
  spec.add_dependency 'rails-i18n', '~> 7.0.3'
  spec.add_dependency 'ratonvirus', '~> 0.3.2'
  spec.add_dependency 'ratonvirus-clamby', '~> 0.3.0'
  spec.add_dependency 'redis', '~> 4.6.0'
  spec.add_dependency 'route_translator', '~> 12.1.0'
  spec.add_dependency 'rspec-rails', '~> 5.1.1'
  spec.add_dependency 'searchkick', '~> 5.0.2'
  spec.add_dependency 'shoulda-callback-matchers', '~> 1.1.4'
  spec.add_dependency 'shoulda-matchers', '~> 5.1.0'
  spec.add_dependency 'sidekiq', '~> 6.4.1'
  spec.add_dependency 'sidekiq-scheduler', '~> 3.1.0'
  spec.add_dependency 'simple_form'
  spec.add_dependency 'slim', '~> 4.1.0'
  spec.add_dependency 'strip_attributes', '~> 1.12.0'
  spec.add_dependency 'strong_migrations', '~> 1.0.0'
  spec.add_dependency 'super_diff', '~> 0.8.0'
  spec.add_dependency 'validate_url', '~> 1.0.13'
  spec.add_dependency 'valid_email', '~> 0.1.4'
  spec.add_dependency 'view_component', '~> 2.52.0'
  spec.add_dependency 'zero-rails_openapi', '~> 2.1.5'
end
