$LOAD_PATH.push File.expand_path("lib", __dir__)

require "schematics/version"

Gem::Specification.new do |spec|
  spec.name        = "schematics"
  spec.version     = Schematics::VERSION
  spec.authors     = ["maxence.derous"]
  spec.email       = ["maxence.derous@gmail.com"]
  spec.homepage    = "http://mygemserver.com"
  spec.summary     = "Summary of Schematics."
  spec.description = "Description of Schematics."
  spec.license     = "Private"
  spec.add_development_dependency "pg", "~> 1.2.3"
  spec.add_development_dependency "rspec-rails", "~> 3.9.0"
  spec.add_development_dependency "rspec_api_documentation", "~> 6.1.0"
  spec.add_development_dependency "simplecov", "~> 0.18.5"
  spec.add_development_dependency "rubocop", "~> 0.76.0"
  spec.add_development_dependency "rubocop-airbnb", "~> 3.0.1"
  spec.add_dependency "rails", "~> 6.0.2.2"
  spec.add_dependency "image_processing", "~> 1.2"
  spec.add_dependency "better_errors", "~> 2.6.0"
  spec.add_dependency "binding_of_caller", "~> 0.8.0"
  spec.add_dependency "pagy", "~> 3.5"
  spec.add_dependency "paranoia", "~> 2.4.2"
  spec.add_dependency "paper_trail", "~> 10.3.1"
  spec.add_dependency "ransack", "~> 2.3.2"
  spec.add_dependency "ransack-enum", "~> 0.2.1"
  spec.add_dependency "rack-attack", "~> 6.2.0"
  spec.add_dependency "annotate", "~> 3.0.3"
  spec.add_dependency "bullet", "~> 6.0.2"
  spec.add_dependency "rack-cors", "~> 1.1.0"
  spec.add_dependency "bcrypt", "~> 3.1.13"
  spec.add_dependency "swagger_ui_engine", "~> 1.1.1"
  spec.add_dependency "swagger-docs", "~> 0.2.8"
  spec.add_dependency "simple_form", "~> 5.0.2"
  spec.add_dependency "client_side_validations", "~> 16.2.0"
  spec.add_dependency "client_side_validations-simple_form", "~> 10.1.0"
  spec.add_dependency "bootstrap", "~> 4.4.1"
  spec.add_dependency "bootswatch", "~> 4.3.1"
  spec.add_dependency "wkhtmltopdf-binary", "~> 0.12.5"
  spec.add_dependency "wicked_pdf", "~> 2.0.2"
  spec.add_dependency "slim", "~> 4.0.1"
  spec.add_dependency "rails-i18n", "~> 6.0.0"
  spec.add_dependency "font_awesome5_rails", "~> 0.9.0"
  spec.add_dependency "friendly_id", "~> 5.3.0"
  spec.add_dependency "jquery-rails", "~> 4.3.5"
  spec.add_dependency "jwt", "~> 2.2.1"
  spec.add_dependency "phonelib", "~> 0.6.40"
  spec.add_dependency "valid_email", "~> 0.1.3"
  spec.add_dependency "validate_url", "~> 1.0.8"
  spec.add_dependency "active_storage_validations", "~> 0.8.5"
  spec.add_dependency "mini_magick", ">= 4.9.5"
  spec.add_dependency "active_link_to", "~> 1.0.5"
  spec.add_dependency "loaf", "~> 0.8.1"
  spec.add_dependency "twitter-typeahead-rails", "~> 0.11.1"
  spec.add_dependency "groupdate", "~> 4.2.0"
  spec.add_dependency "chartkick", "~> 3.3.0"
  spec.add_dependency "humanize", "~> 2.4.0"
  spec.add_dependency "active_storage_base64", "~> 1.1.0"
  spec.add_dependency "json_schemer", "~> 0.2.11"
  spec.add_dependency "route_translator", "~> 7.1.2"
  spec.add_dependency "google-cloud-translate", "~> 2.3.0"
  spec.add_dependency "date_validator", "~> 0.9.0"
  spec.add_dependency "oj", "~> 3.10.6"
  spec.add_dependency "active_model_serializers", "~> 0.10.10"
  spec.add_dependency "acts_as_singleton", "~> 0.0.8"
  spec.add_dependency "animate-rails", "~> 1.0.10"
  spec.add_dependency "title", "~> 0.0.7"
  spec.add_dependency "sprockets", "~> 3.7.2"
  spec.add_dependency "best_in_place"
  spec.add_dependency "jquery-ui-rails"
  spec.add_dependency "thor", "~> 0.20.3"
  spec.metadata["allowed_push_host"] = "http://mygemserver.com"
  spec.files = Dir["{app,config,db,lib}/**/*", "README.md"]
end
