services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  clamav:
    image: clamav/clamav:latest
    ports:
      - 3310:3310
    volumes:
      - clamav-data:/var/lib/clamav
  chrome:
    image: browserless/chrome:latest
    ports:
      - 3333:3000
  web:
    build:
      context: $PWD
      dockerfile: $DOCKERFILE_PATH
    ports:
      - 3000:3000
    volumes:
      - storage-data:/app/storage
    depends_on:
      - postgres
      - clamav
      - chrome
    environment:
      - PRIMARY_DATABASE_URL=postgres://postgres@postgres
      - SEARCH_DATABASE_URL=postgres://postgres@postgres
      - CHROME_URL=http://chrome:3333
      - SCHEMATICS_MASTER_KEY=$SCHEMATICS_MASTER_KEY
volumes:
  postgres-data:
  clamav-data:
  storage-data:
