version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./config/docker/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
      - db
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/app
volumes:
  dbdata:
