#!/bin/bash -e

docker login
docker build -t backofficeapp/back-office:1.0.0 --no-cache .
docker build -t backofficeapp/back-office:1.0.0-core --build-arg CORE=true --no-cache .
docker tag backofficeapp/back-office:1.0.0 backofficeapp/back-office:latest
docker tag backofficeapp/back-office:1.0.0-core backofficeapp/back-office:latest-core
docker push backofficeapp/back-office:1.0.0
docker push backofficeapp/back-office:1.0.0-core
docker push backofficeapp/back-office:latest
docker push backofficeapp/back-office:latest-core
