require 'json'
require 'csv'
require 'pagy'
require 'pagy/extras/searchkick'
require 'pagy/extras/array'
require 'pagy/extras/headers'
require 'pagy/extras/bootstrap'
require 'pagy/extras/i18n'
require 'paranoia'
require 'paper_trail'
require 'rails'
require 'action_controller'
require 'binding_of_caller'
require 'searchkick'
require 'rack/attack'
require 'rack/cors'
require 'simple_form'
require 'client_side_validations'
require 'client_side_validations/simple_form'
require 'bootstrap'
require 'bootswatch'
require 'wicked_pdf'
require 'slim'
require 'rails-i18n'
require 'font_awesome5_rails'
require 'friendly_id'
require 'jquery-rails'
require 'jwt'
require 'phonelib'
require 'valid_email'
require 'validate_url'
require 'active_storage_validations'
require 'mini_magick'
require 'active_link_to'
require 'loaf'
require 'twitter-typeahead-rails'
require 'groupdate'
require 'chartkick'
require 'humanize'
require 'active_storage_base64'
require 'json_schemer'
require 'route_translator'
require 'date_validator'
require 'google/cloud/translate'
require 'oj'
require 'active_model_serializers'
require 'acts_as_singleton'
require 'ancestry'
require 'animate-rails'
require 'title'
require 'best_in_place'
require 'jquery-ui-rails'
require 'rails-erd'
require 'bootstrap-email'
require 'interactor'
require 'rails-timeago'
require 'cancancan'
require 'rspec_api_documentation'
require 'grape-swagger-rails'
require 'json_web_token'
require 'array'
require 'string'
require 'view_component/engine'
require 'schematics/engine'
require 'schematics/schema'
require 'schematics/patches/rails/generators/generated_attribute'

module Schematics
  module Specs
    autoload :Acceptance, 'schematics/specs/acceptance'
    autoload :Helpers,    'schematics/specs/helpers'
  end

  module Tests
    autoload :Controller, 'schematics/tests/controller'
    autoload :Model,      'schematics/tests/model'
    autoload :System,     'schematics/tests/system'
  end

  SCHEMA = Schema.instance
end
