---
:concurrency: 2
:queues:
  - default
  - searchkick
  - rollbar
  - mailers
:scheduler:
  :dynamic: true
  :schedule:
    schematics/database_backup_job:
      cron: 0 0 * * *
      class: Schematics::DatabaseBackupJob
    schematics/clean_database_backups_job:
      cron: 0 1 * * *
      class: Schematics::CleanDatabaseBackupsJob
    schematics/clean_comparisons_job:
      cron: 0 1 * * *
      class: Schematics::CleanComparisonsJob
    schematics/clean_drafts_job:
      cron: 0 1 * * *
      class: Schematics::CleanDraftsJob
    schematics/clean_searches_job:
      cron: 0 1 * * *
      class: Schematics::CleanSearchesJob
    schematics/clean_sessions_job:
      cron: 0 1 * * *
      class: Schematics::CleanSessionsJob
    schematics/clean_api_requests_job:
      cron: 0 1 * * *
      class: Schematics::CleanApiRequestsJob
    schematics/load_licence_job:
      cron: 0 1 * * *
      class: Schematics::LoadLicenceJob
