---
:concurrency: 2
:queues:
  - default
  - migrations
  - imports
  - exports
  - mailers
  - webhooks
  - backups
  - cleanups
  - searchkick
  - rollbar
:scheduler:
  :dynamic: true
  :schedule:
    schematics/database_backup_job:
      cron: 0 0 * * *
      class: Schematics::DatabaseBackupJob
    schematics/clean_database_backups_job:
      cron: 0 1 * * *
      class: Schematics::CleanDatabaseBackupsJob
    schematics/clean_comparisons_job:
      cron: 0 1 * * *
      class: Schematics::CleanComparisonsJob
    schematics/clean_drafts_job:
      cron: 0 1 * * *
      class: Schematics::CleanDraftsJob
    schematics/clean_searches_job:
      cron: 0 1 * * *
      class: Schematics::CleanSearchesJob
    schematics/clean_sessions_job:
      cron: 0 1 * * *
      class: Schematics::CleanSessionsJob
    schematics/clean_api_requests_job:
      cron: 0 1 * * *
      class: Schematics::CleanApiRequestsJob
    schematics/clean_api_keys_job:
      cron: 0 1 * * *
      class: Schematics::CleanApiKeysJob
    schematics/clean_meetings_job:
      cron: 0 1 * * *
      class: Schematics::CleanMeetingsJob
    schematics/clean_tasks_job:
      cron: 0 1 * * *
      class: Schematics::CleanTasksJob
    schematics/clean_imports_job:
      cron: 0 1 * * *
      class: Schematics::CleanImportsJob
    schematics/clean_messages_job:
      cron: 0 1 * * *
      class: Schematics::CleanMessagesJob
    schematics/load_subscription_job:
      cron: 0 1 * * *
      class: Schematics::LoadSubscriptionJob
    schematics/migrate_core_job:
      cron: 0 1 * * *
      class: Schematics::MigrateCoreJob
