development:
  adapter: solid_cable
  connects_to:
    shards:
      cable:
        writing: cable

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    shards:
      cable:
        writing: cable
