---
ActionText::RichText:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
FriendlyId::Slug:
  enabled: false
PaperTrail::Version:
  enabled: false
Schematics::Version:
  enabled: false
Import:
  file:
    ColumnPresenceChecker:
      enabled: false
Message:
  content:
    ColumnPresenceChecker:
      enabled: false
