default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  connect_timeout: 1
  checkout_timeout: 1
  variables:
    statement_timeout: <%= ENV.fetch('STATEMENT_TIMEOUT', '5s') %>

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
    migrations_paths: db/migrate
  search:
    <<: *default
    database: storage/development_search.sqlite3
    migrations_paths: db/search_migrate
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
    migrations_paths: db/migrate
  search:
    <<: *default
    database: storage/test_search.sqlite3
    migrations_paths: db/search_migrate

production:
  primary:
    <% if ENV['DATABASE_URL'].present? %>
    <<: *postgresql
    url: <%= ENV['DATABASE_URL'] %>
    database: production
    <% else %>
    <<: *default
    database: storage/production.sqlite3
    <% end %>
    migrations_paths: db/migrate
  search:
    <<: *default
    database: storage/production_search.sqlite3
    migrations_paths: db/search_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
