sqlite3: &sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000

development:
  primary:
    <<: *sqlite3
    database: storage/<%= ENV.fetch('DATABASE', 'demo') %>/development.sqlite3
    migrations_paths: db/<%= ENV.fetch('DATABASE', 'demo') %>/migrate
  queue:
    <<: *sqlite3
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite3
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *sqlite3
    database: storage/<%= ENV.fetch('DATABASE', 'demo') %>/test.sqlite3
    migrations_paths: db/<%= ENV.fetch('DATABASE', 'demo') %>/migrate

production:
  primary:
    <<: *sqlite3
    database: storage/<%= ENV.fetch('DATABASE', 'demo') %>/production.sqlite3
    migrations_paths: db/<%= ENV.fetch('DATABASE', 'demo') %>/migrate
  queue:
    <<: *sqlite3
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate

on_premise:
  primary:
    <<: *sqlite3
    database: storage/<%= ENV.fetch('DATABASE', 'demo') %>/production.sqlite3
    migrations_paths: db/<%= ENV.fetch('DATABASE', 'demo') %>/migrate
  queue:
    <<: *sqlite3
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *sqlite3
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
