---
data:
  read:
    - config/locales/**/%{locale}.yml
  yaml:
    write:
      line_width: -1
search:
  paths:
    - app/
    - lib/
  relative_roots:
    - app/components
    - app/controllers
    - app/mailers
    - app/views
ignore_missing:
  - activerecord.*
  - activemodel.*
  - routes.*
  - titles.*
  - errors.*
  - attributes.*
  - open_api.*
  - schematics.*
  - sessions.*
  - javascript.*
  - pagy.*
  - date.*
  - time.*
  - i18n.inflections.gender.*
  - 'true'
  - 'false'
  - line
  - by
  - of
ignore_unused:
  - activerecord.*
  - activemodel.*
  - routes.*
  - titles.*
  - errors.*
  - attributes.*
  - open_api.*
  - schematics.*
  - sessions.*
  - javascript.*
  - pagy.*
  - date.*
  - time.*
  - i18n.inflections.gender.*
  - 'true'
  - 'false'
  - line
  - by
  - of
