data:
  read:
    - config/locales/**/%{locale}.yml
  yaml:
    write:
      line_width: -1
search:
  paths:
    - app/
    - lib/
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/views
    - app/components
  exclude:
    - lib/csv_importer.rb
# translation:
  # google_translate_api_key: TODO
ignore_missing:
  - activerecord.*
  - routes.*
  - simple_form.*
  - titles.*
  - errors.*
  - attributes.*
  - schematics.*
  - 'true'
  - 'false'
ignore_unused:
  - activerecord.*
  - routes.*
  - simple_form.*
  - titles.*
  - errors.*
  - attributes.*
  - schematics.*
  - 'true'
  - 'false'
