# Copyright © 2025 Dev & Software. All rights reserved.

# THIS SOFTWARE IS PROPRIETARY AND CONFIDENTIAL. UNAUTHORIZED COPYING, DISTRIBUTION, MODIFICATION,
# REVERSE ENGINEERING, OR DISCLOSURE IS STRICTLY PROHIBITED.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER
# LIABILITY ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE OR ITS USE.

# frozen_string_literal: true

pin 'application'
pin 'controllers', to: 'controllers/index.js'
pin '@rails/actiontext', to: 'actiontext.esm.js'
pin '@hotwired/turbo-rails', to: 'turbo.js'
pin '@hotwired/stimulus', to: 'stimulus.js'
pin '@hotwired/stimulus-loading', to: 'stimulus-loading.js'
pin 'chartkick', to: 'chartkick.js'
pin 'Chart.bundle', to: 'Chart.bundle.js'

pin 'controllers/dropdowns/address_autocomplete_dropdown_controller'
pin 'controllers/dropdowns/association_dropdown_controller'
pin 'controllers/dropdowns/colors_dropdown_controller'
pin 'controllers/dropdowns/fa_icons_dropdown_controller'
pin 'controllers/schema_editor/association_dropdown_controller'
pin 'controllers/schema_editor/descriptor_dropdown_controller'
pin 'controllers/schema_editor/habtm_association_dropdown_controller'
pin 'controllers/schema_editor/modal_dropdown_controller'
pin 'controllers/schema_editor/special_characters_controller'
pin 'controllers/schema_editor/variable_typeahead_controller'
pin 'controllers/application_controller'
pin 'controllers/application'
pin 'controllers/attachment_controller'
pin 'controllers/attachments_previewer_controller'
pin 'controllers/auto_save_controller'
pin 'controllers/autosize_controller'
pin 'controllers/bulk_action_controller'
pin 'controllers/clipboard_controller'
pin 'controllers/code_editor_controller'
pin 'controllers/comparison_controller'
pin 'controllers/count_up_controller'
pin 'controllers/dropdown_controller'
pin 'controllers/filters_controller'
pin 'controllers/generate_file_in_background_controller'
pin 'controllers/hotkey_controller'
pin 'controllers/kanban_controller'
pin 'controllers/mentions_controller'
pin 'controllers/modal_controller'
pin 'controllers/nested_form_controller'
pin 'controllers/network_controller'
pin 'controllers/notification_center_controller'
pin 'controllers/offcanvas_controller'
pin 'controllers/one_time_password_controller'
pin 'controllers/password_controller'
pin 'controllers/popover_controller'
pin 'controllers/search_bar_controller'
pin 'controllers/sidebar_controller'
pin 'controllers/sortable_controller'
pin 'controllers/swagger_controller'
pin 'controllers/switch_theme_controller'
pin 'controllers/timeago_controller'
pin 'controllers/toast_controller'
pin 'controllers/tooltip_controller'
pin 'controllers/typeahead_controller'
pin 'controllers/viewer_settings_controller'

pin '@fortawesome/fontawesome-free', to: '@fortawesome/fontawesome-free/js/fontawesome.js'
pin '@github/hotkey', to: '@github/hotkey/dist/index.js'
pin '@popperjs/core', to: 'https://unpkg.com/@popperjs/core@2.11.8/dist/esm/index.js'
pin 'autosize', to: 'autosize/dist/autosize.esm.js'
pin 'bootstrap', to: 'bootstrap/dist/js/bootstrap.esm.js'
pin 'file-saver', to: 'file-saver-es/src/FileSaver.js'
pin 'monaco-editor', to: 'https://cdn.jsdelivr.net/npm/monaco-editor@0.55.1/+esm'
pin 'path', to: 'https://ga.jspm.io/npm:@jspm/core@2.1.0/nodelibs/browser/path.js'
pin 'pluralize', to: 'pluralize-esm/dist/index.js'
pin 'rollbar', to: 'https://ga.jspm.io/npm:rollbar@2.26.5/dist/rollbar.umd.js'
pin 'sortablejs', to: 'sortablejs/modular/sortable.esm.js'
pin 'swagger-ui-dist', to: 'https://ga.jspm.io/npm:swagger-ui-dist@5.31.0/index.js'
pin 'timeago.js', to: 'https://unpkg.com/timeago.js@4.0.2/esm/index.js'
pin 'timeago.fr.js', to: 'https://unpkg.com/timeago.js@4.0.2/esm/lang/fr.js'
pin 'timeago.it.js', to: 'https://unpkg.com/timeago.js@4.0.2/esm/lang/it.js'
pin 'tom-select', to: 'tom-select/dist/esm/tom-select.complete.js'
pin 'tributejs', to: 'tributejs/dist/tribute.esm.js'
pin 'trix', to: 'trix/dist/trix.esm.js'
