type: object
properties:
  id:
    type: string
    description: A random RFC 4122 UUID
    pattern: \w{8}-\w{4}-\w{4}-\w{4}-\w{12}
  name:
    type: string
    description: The entity name in snake case
    not:
      enum: |
        <%=
          Tenant
            .schema
            .entities
            .select(&:core?)
            .map(&:name)
            .concat(Schematics::Entities::Entity::NAME_DENYLIST)
        %>
  options:
    type: object
    properties:
      descriptor:
        type: string
        description: The property name which represents the most the entity
      icon:
        type: string
        enum: <%= Schematics::Options::Icon.collection.map(&:to_s) %>
        description: An icon which represents the entity in snake case
  attributes:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
          description: A random RFC 4122 UUID
          pattern: \w{8}-\w{4}-\w{4}-\w{4}-\w{12}
        name:
          type: string
          pattern: .*(?<!_id)$
          description: The property name in snake case
          not:
            enum: |
              <%=
                ActiveRecord::AttributeMethods
                  .dangerous_attribute_methods
                  .dup
                  .merge(Schematics::Behaviours::Nameable::NAME_DENYLIST)
                  .merge(Schematics::Trackable::DENYLIST)
                  .to_a
                  .map(&:to_s)
              %>
        type:
          type: string
          enum: <%= Schematics::Attributes::Attribute.collection.map(&:type) %>
          description: The property type in snake case
      required:
        - id
        - name
        - type
  required:
    - id
    - name
    - options
    - attributes
