---
schematics/clean_data_job:
  class: Schematics::CleanDataJob
  schedule: every hour
schematics/generate_backup_job:
  class: Schematics::GenerateBackupJob
  schedule: every day at midnight
schematics/check_license_job:
  class: Schematics::CheckLicenseJob
  schedule: every day at midnight
schematics/migrate_core_job:
  class: Schematics::MigrateCoreJob
  schedule: every day at 1am
schematics/migrate_schema_job:
  class: Schematics::MigrateSchemaJob
  schedule: every day at 2am
