---
workers:
  - queues:
    - default
    - migrations
    - imports
    - exports
    - mailers
    - notifications
    - webhooks
    - backups
    - cleanups
    - searchkick
    - rollbar
dispatchers:
  - polling_interval: 1
    batch_size: 500
    recurring_tasks:
      schematics/data_cleaning_job:
        schedule: every hour
        class: Schematics::DataCleaningJob
      schematics/database_backup_job:
        schedule: every day at midnight
        class: Schematics::DatabaseBackupJob
      schematics/load_subscription_job:
        schedule: every day at midnight
        class: Schematics::LoadSubscriptionJob
      schematics/clean_database_backups_job:
        schedule: every day at 1am
        class: Schematics::CleanDatabaseBackupsJob
      schematics/clean_tasks_job:
        schedule: every day at 1am
        class: Schematics::CleanTasksJob
      schematics/clean_messages_job:
        schedule: every day at 1am
        class: Schematics::CleanMessagesJob
      schematics/migrate_core_job:
        schedule: every day at 1am
        class: Schematics::MigrateCoreJob
      schematics/migrate_schema_job:
        schedule: every day at 2am
        class: Schematics::MigrateSchemaJob
