test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

amazon:
  service: TenantS3
  access_key_id: <%= ENV.fetch('AWS_ACCESS_KEY_ID', Schematics::Engine.credentials.aws.access_key_id) %>
  secret_access_key: <%= ENV.fetch('AWS_SECRET_ACCES_KEY', Schematics::Engine.credentials.aws.secret_access_key) %>
  region: <%= ENV.fetch('AWS_REGION', 'us-east-1') %>
  bucket: <%= Tenant.domain %>
