postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  connect_timeout: 1
  checkout_timeout: 1
  variables:
    statement_timeout: <%= ENV.fetch('STATEMENT_TIMEOUT', '5s') %>

sqlite3: &sqlite3
  adapter: sqlite3
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5_000

development:
  primary:
    <<: *postgresql
    database: <%= Tenant.database_name %>_development
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *sqlite3
    database: storage/development_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate
  cable:
    <<: *sqlite3
    database: storage/development_cable_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cable_migrate
  cache:
    <<: *sqlite3
    database: storage/development_cache_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cache_migrate
  queue:
    <<: *sqlite3
    database: storage/development_queue_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_queue_migrate

test:
  primary:
    <<: *sqlite3
    database: storage/test_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *sqlite3
    database: storage/test_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate

production:
  primary:
    <<: *postgresql
    database: <%= Tenant.database_name %>_production
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *sqlite3
    database: storage/production_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate
  cable:
    <<: *sqlite3
    database: storage/production_cable_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cable_migrate
  cache:
    <<: *sqlite3
    database: storage/production_cache_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cache_migrate
  queue:
    <<: *sqlite3
    database: storage/production_queue_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_queue_migrate
