default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5_000

development:
  primary:
    <<: *default
    database: storage/development_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *default
    database: storage/development_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate
  cable:
    <<: *default
    database: storage/development_cable_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cable_migrate
  cache:
    <<: *default
    database: storage/development_cache_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cache_migrate
  queue:
    <<: *default
    database: storage/development_queue_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_queue_migrate

test:
  primary:
    <<: *default
    database: storage/test_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *default
    database: storage/test_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate

production:
  primary:
    <<: *default
    database: storage/production_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_migrate
  search:
    <<: *default
    database: storage/production_search_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_search_migrate
  cable:
    <<: *default
    database: storage/production_cable_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cable_migrate
  cache:
    <<: *default
    database: storage/production_cache_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_cache_migrate
  queue:
    <<: *default
    database: storage/production_queue_<%= Tenant.database_name %>.sqlite3
    migrations_paths: db/<%= Tenant.database_name %>_queue_migrate
