name: CI
on: [push]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop
  reek:
    name: Reek
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Reek
        run: bundle exec reek
  slim_lint:
    name: Slim lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Slim lint
        run: bundle exec slim-lint app
  stylelint:
    name: Stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable --immutable-cache --check-cache
      - name: Run stylelint
        run: yarn stylelint
  i18n:
    name: i18n lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run i18n lint
        run: bundle exec i18n-tasks health
  standard:
    name: StandardJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: yarn
      - name: Install dependencies
        run: yarn --immutable --immutable-cache --check-cache
      - name: Run standard
        run: yarn lint
  rspec:
    name: RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec ./spec/lib --require schematics
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run brakeman
        run: bundle exec brakeman --no-pager --no-exit-on-error
  bundler_audit:
    name: Bundler audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run bundler-audit
        run: bundle exec bundle-audit
