name: Linters

on: [push]

jobs:
  rubucop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: RuboCop Linter
        uses: andrewmcodes/rubocop-linter-action@v3.3.0
        with:
          action_config_path: '.github/config/rubocop_linter_action.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reek
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: reek
        uses: reviewdog/action-reek@v1
        with:
          REEK_VERSION: Gemfile
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
