name: Shared
on: [workflow_call]
jobs:
  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: artplan1/brakeman-action@v1.2.1
  bundler_audit:
    name: Bundler audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: andrewmcodes/bundler-audit-action@main
