name: Test
on: [workflow_dispatch]
env:
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
jobs:
  rspec:
    name: RSpec
    runs-on: ubuntu-24.04
    steps:
      - uses: browser-actions/setup-chrome@v2
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.2.8
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libvips-dev ffmpeg graphviz
      - name: Generate test tenant
        run: |
          bin/rails db:create
          bin/rails schematics:generate
          bin/rails db:migrate
      - name: Run ability tests
        if: always()
        run: bundle exec rspec spec/abilities
      - name: Run component tests
        if: always()
        run: bundle exec rspec spec/components
      - name: Run db tests
        if: always()
        run: bundle exec rspec spec/db
      - name: Run feature tests
        if: always()
        run: bundle exec rspec spec/features
      - name: Run generator tests
        if: always()
        run: bundle exec rspec spec/generators
      - name: Run mailer tests
        if: always()
        run: bundle exec rspec spec/mailers
      - name: Run mapper tests
        if: always()
        run: bundle exec rspec spec/mappers
      - name: Run model tests
        if: always()
        run: bundle exec rspec spec/models
      - name: Run query tests
        if: always()
        run: bundle exec rspec spec/queries
      - name: Run routing tests
        if: always()
        run: bundle exec rspec spec/routing
      - name: Run serializer tests
        if: always()
        run: bundle exec rspec spec/serializers
      - name: Run request tests
        if: always()
        run: bundle exec rspec spec/requests
      - name: Run interactor tests
        if: always()
        run: bundle exec rspec spec/interactors
      - name: Run job tests
        if: always()
        run: bundle exec rspec spec/jobs
